#!/usr/bin/env python3
"""clear_parse_jargon_cache.py — surgically drop cached LSJ/word-study syntheses
that recite grammatical parsing ("genitive singular", "aorist participle", …).

Context: the word-study definition is generated by synthesize_lsj_summary and cached
in lsj.summary_json (keyed by `key`) and abp_ext.summary_json (keyed by `strongs`).
Each blob is JSON with optional `general` (str), `context` (dict verse->str), and
`sections`. We added a prompt rule telling Haiku NOT to state the grammatical parse;
this clears only the already-cached syntheses that still do, so they regenerate on
next view. Everything else in the blob (sections, clean summaries) is preserved.

READ-ONLY by default (dry-run). Pass --apply to write. Pass a db path as arg 1
(default: bible.db). Run on PythonAnywhere — bible.db is not local.

  python clear_parse_jargon_cache.py            # dry-run on bible.db
  python clear_parse_jargon_cache.py --apply     # commit
"""
import json
import re
import sqlite3
import sys

# Unambiguous grammatical-parse tokens. Deliberately EXCLUDES words that double as
# ordinary meaning ("present", "singular", "plural", "perfect", "noun", "verb",
# "active") to avoid clearing legitimate meaning-focused definitions. A synthesis is
# flagged only if it cites a Greek case name, a tense/mood name, or "Nth person".
JARGON = re.compile(
    r"\b("
    r"nominative|genitive|dative|accusative|vocative"
    r"|aorist|imperfect|pluperfect"
    r"|participle|infinitive|subjunctive|optative|indicative|imperative"
    r"|(?:middle|passive|active)\s+voice"
    r"|(?:1st|2nd|3rd|first|second|third)\s+person"
    r")\b",
    re.IGNORECASE,
)


def clean_blob(raw):
    """Return (new_json_str, removed_labels) or (None, []) if nothing to change."""
    try:
        sj = json.loads(raw)
    except Exception:
        return None, []
    if not isinstance(sj, dict):
        return None, []

    removed = []
    if isinstance(sj.get("general"), str) and JARGON.search(sj["general"]):
        removed.append("general")
        sj.pop("general")

    ctx = sj.get("context")
    if isinstance(ctx, dict):
        for k in [k for k, v in ctx.items() if isinstance(v, str) and JARGON.search(v)]:
            removed.append(f"context[{k}]")
            ctx.pop(k)
        if not ctx:
            sj.pop("context", None)

    if not removed:
        return None, []
    return json.dumps(sj, ensure_ascii=False), removed


def process(conn, table, id_col, apply):
    rows = conn.execute(
        f"SELECT {id_col} AS id, summary_json FROM {table} "
        f"WHERE summary_json IS NOT NULL AND summary_json != ''"
    ).fetchall()
    n_rows = n_clears = 0
    for r in rows:
        new_json, removed = clean_blob(r["summary_json"])
        if not removed:
            continue
        n_rows += 1
        n_clears += len(removed)
        print(f"  {table}[{r['id']}]: drop {', '.join(removed)}")
        if apply:
            conn.execute(
                f"UPDATE {table} SET summary_json = ? WHERE {id_col} = ?",
                (new_json, r["id"]),
            )
    return n_rows, n_clears


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    apply = "--apply" in sys.argv
    db_path = args[0] if args else "bible.db"

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    print(f"{'APPLY' if apply else 'DRY-RUN'} on {db_path}\n")

    total_rows = total_clears = 0
    for table, id_col in (("lsj", "key"), ("abp_ext", "strongs")):
        print(f"== {table} ==")
        nr, nc = process(conn, table, id_col, apply)
        print(f"   {nr} rows, {nc} cached syntheses flagged\n")
        total_rows += nr
        total_clears += nc

    if apply:
        conn.commit()
        print(f"COMMITTED: cleared {total_clears} syntheses across {total_rows} rows.")
    else:
        print(f"DRY-RUN: would clear {total_clears} syntheses across {total_rows} rows.")
        print("Re-run with --apply to commit.")
    conn.close()


if __name__ == "__main__":
    main()
