// ============================================================
// LIBRARY DATA — canon, Amos 1 text (ABP markup + KJV), lexicon
// Markup in ABP strings:
//   [ ]          → word-order bracket group
//   ^N           → superscript Greek word-order number
//   *word*       → supplied/italic word
//   {Eng|Strong} → clickable lemma  (append |active to preselect)
// ============================================================

// ---- Canon (66 books, chapter counts) ----
const BOOKS = [
  // Old Testament
  { ab: "Gen", name: "Genesis", ch: 50, div: "Law", t: "OT" },
  { ab: "Exo", name: "Exodus", ch: 40, div: "Law", t: "OT" },
  { ab: "Lev", name: "Leviticus", ch: 27, div: "Law", t: "OT" },
  { ab: "Num", name: "Numbers", ch: 36, div: "Law", t: "OT" },
  { ab: "Deu", name: "Deuteronomy", ch: 34, div: "Law", t: "OT" },
  { ab: "Jos", name: "Joshua", ch: 24, div: "History", t: "OT" },
  { ab: "Jdg", name: "Judges", ch: 21, div: "History", t: "OT" },
  { ab: "Rut", name: "Ruth", ch: 4, div: "History", t: "OT" },
  { ab: "1Sa", name: "1 Samuel", ch: 31, div: "History", t: "OT" },
  { ab: "2Sa", name: "2 Samuel", ch: 24, div: "History", t: "OT" },
  { ab: "1Ki", name: "1 Kings", ch: 22, div: "History", t: "OT" },
  { ab: "2Ki", name: "2 Kings", ch: 25, div: "History", t: "OT" },
  { ab: "1Ch", name: "1 Chronicles", ch: 29, div: "History", t: "OT" },
  { ab: "2Ch", name: "2 Chronicles", ch: 36, div: "History", t: "OT" },
  { ab: "Ezr", name: "Ezra", ch: 10, div: "History", t: "OT" },
  { ab: "Neh", name: "Nehemiah", ch: 13, div: "History", t: "OT" },
  { ab: "Est", name: "Esther", ch: 10, div: "History", t: "OT" },
  { ab: "Job", name: "Job", ch: 42, div: "Wisdom", t: "OT" },
  { ab: "Psa", name: "Psalms", ch: 150, div: "Wisdom", t: "OT" },
  { ab: "Pro", name: "Proverbs", ch: 31, div: "Wisdom", t: "OT" },
  { ab: "Ecc", name: "Ecclesiastes", ch: 12, div: "Wisdom", t: "OT" },
  { ab: "Sng", name: "Song of Solomon", ch: 8, div: "Wisdom", t: "OT" },
  { ab: "Isa", name: "Isaiah", ch: 66, div: "Major Prophets", t: "OT" },
  { ab: "Jer", name: "Jeremiah", ch: 52, div: "Major Prophets", t: "OT" },
  { ab: "Lam", name: "Lamentations", ch: 5, div: "Major Prophets", t: "OT" },
  { ab: "Eze", name: "Ezekiel", ch: 48, div: "Major Prophets", t: "OT" },
  { ab: "Dan", name: "Daniel", ch: 12, div: "Major Prophets", t: "OT" },
  { ab: "Hos", name: "Hosea", ch: 14, div: "Minor Prophets", t: "OT" },
  { ab: "Joe", name: "Joel", ch: 3, div: "Minor Prophets", t: "OT" },
  { ab: "Amo", name: "Amos", ch: 9, div: "Minor Prophets", t: "OT" },
  { ab: "Oba", name: "Obadiah", ch: 1, div: "Minor Prophets", t: "OT" },
  { ab: "Jon", name: "Jonah", ch: 4, div: "Minor Prophets", t: "OT" },
  { ab: "Mic", name: "Micah", ch: 7, div: "Minor Prophets", t: "OT" },
  { ab: "Nah", name: "Nahum", ch: 3, div: "Minor Prophets", t: "OT" },
  { ab: "Hab", name: "Habakkuk", ch: 3, div: "Minor Prophets", t: "OT" },
  { ab: "Zep", name: "Zephaniah", ch: 3, div: "Minor Prophets", t: "OT" },
  { ab: "Hag", name: "Haggai", ch: 2, div: "Minor Prophets", t: "OT" },
  { ab: "Zec", name: "Zechariah", ch: 14, div: "Minor Prophets", t: "OT" },
  { ab: "Mal", name: "Malachi", ch: 4, div: "Minor Prophets", t: "OT" },
  // New Testament
  { ab: "Mat", name: "Matthew", ch: 28, div: "Gospels", t: "NT" },
  { ab: "Mar", name: "Mark", ch: 16, div: "Gospels", t: "NT" },
  { ab: "Luk", name: "Luke", ch: 24, div: "Gospels", t: "NT" },
  { ab: "Joh", name: "John", ch: 21, div: "Gospels", t: "NT" },
  { ab: "Act", name: "Acts", ch: 28, div: "History", t: "NT" },
  { ab: "Rom", name: "Romans", ch: 16, div: "Pauline Epistles", t: "NT" },
  { ab: "1Co", name: "1 Corinthians", ch: 16, div: "Pauline Epistles", t: "NT" },
  { ab: "2Co", name: "2 Corinthians", ch: 13, div: "Pauline Epistles", t: "NT" },
  { ab: "Gal", name: "Galatians", ch: 6, div: "Pauline Epistles", t: "NT" },
  { ab: "Eph", name: "Ephesians", ch: 6, div: "Pauline Epistles", t: "NT" },
  { ab: "Phi", name: "Philippians", ch: 4, div: "Pauline Epistles", t: "NT" },
  { ab: "Col", name: "Colossians", ch: 4, div: "Pauline Epistles", t: "NT" },
  { ab: "1Th", name: "1 Thessalonians", ch: 5, div: "Pauline Epistles", t: "NT" },
  { ab: "2Th", name: "2 Thessalonians", ch: 3, div: "Pauline Epistles", t: "NT" },
  { ab: "1Ti", name: "1 Timothy", ch: 6, div: "Pauline Epistles", t: "NT" },
  { ab: "2Ti", name: "2 Timothy", ch: 4, div: "Pauline Epistles", t: "NT" },
  { ab: "Tit", name: "Titus", ch: 3, div: "Pauline Epistles", t: "NT" },
  { ab: "Phm", name: "Philemon", ch: 1, div: "Pauline Epistles", t: "NT" },
  { ab: "Heb", name: "Hebrews", ch: 13, div: "General Epistles", t: "NT" },
  { ab: "Jas", name: "James", ch: 5, div: "General Epistles", t: "NT" },
  { ab: "1Pe", name: "1 Peter", ch: 5, div: "General Epistles", t: "NT" },
  { ab: "2Pe", name: "2 Peter", ch: 3, div: "General Epistles", t: "NT" },
  { ab: "1Jo", name: "1 John", ch: 5, div: "General Epistles", t: "NT" },
  { ab: "2Jo", name: "2 John", ch: 1, div: "General Epistles", t: "NT" },
  { ab: "3Jo", name: "3 John", ch: 1, div: "General Epistles", t: "NT" },
  { ab: "Jud", name: "Jude", ch: 1, div: "General Epistles", t: "NT" },
  { ab: "Rev", name: "Revelation", ch: 22, div: "Apocalyptic", t: "NT" },
];

// ---- Amos 1 — ABP English (with study markup) ----
const AMOS1_ABP = [
  "*The* words of {Amos|H5986}, which took place in Kirjath Jearim of {Tekoa|H8620}, which he saw concerning {Jerusalem|H3389} in *the* days of {Uzziah|H5818} king of {Judah|H3063}, and in *the* days of {Jeroboam|H3379} son Joash king of {Israel|H3478}, [^3before ^1two ^2years] *the* earthquake.",
  "And he said, *The* LORD [^2from ^3{Zion|H6726} ^1uttered a sound,] and from {Jerusalem|H3389} he gave his voice; and [^5mourned ^1*the* ^2pastures ^3of the ^4shepherds,] and [^4was dried up ^1*the* ^2top ^3of {Carmel|H3760}.]",
  "And LORD *the* said, For the three impious deeds of {Damascus|G1154|active}, even for the four, I will not turn away from him. Because they sawed [^2saws ^1by iron] the ones [^2in ^3*the* womb ^1having one] in {Gilead|H1568}.",
  "And I will send a fire unto the house of {Hazael|H2371}, and it shall devour the foundations of *the* son of {Hadad|H1130}.",
  "And I shall break *the* bars of {Damascus|G1154}, and I will utterly destroy the inhabitants of *the* plain of On; and I will cut in pieces a tribe of *the* men of {Eden|H5731}; and [^4shall be captured ^2people ^3of {Syria|G4947} ^1select,] says *the* LORD.",
  "Thus says *the* LORD, For the three impious deeds of {Gaza|H5804}, and for the four, I will not turn away from them. Because of their capturing the captivity of {Solomon|H8010}, to close *them* up in {Edom|H123}.",
  "And I will send out fire upon the walls of {Gaza|H5804}, and it shall devour her foundations.",
  "And I will utterly destroy the inhabitants of {Ashdod|H795}, and shall lift away a tribe from {Ashkelon|H831}, and I will bring my hand upon {Ekron|H6138}. And [^5shall be destroyed ^1*the* ^2rest ^3of the ^4{Philistines|H6430},] says *the* LORD.",
  "Thus says *the* LORD, For the three impious deeds of {Tyre|H6865}, even for the four, I will not turn away from them. Because of their delivering up the captivity of {Solomon|H8010} into {Edom|H123}, and they remembered not the covenant of brethren.",
  "And I will send out a fire upon the walls of {Tyre|H6865}, and it shall devour her foundations.",
  "Thus says *the* LORD, For the three impious deeds of {Edom|H123}, and for the four, I will not turn away from them. Because of their pursuing [^2with ^3*the* broadsword ^1their brother,] and they corrupted *the* mother upon the earth; and they seized for plunder a testimony of his shuddering, and his violence he kept to victory.",
  "And I will send out a fire upon {Teman|H8487}, and it shall devour the foundations of her walls.",
  "Thus says *the* LORD, For the three impious deeds of *the* sons of {Ammon|H5983}, and for the four, I will not turn away from him. Because of their ripping up the ones [^1with child ^2of the] {Gilead|H1568}ites, so as to widen their borders.",
  "And I will light a fire upon the walls of {Rabbah|H7237}, and it shall devour her foundations with a shout in *the* day of war, and she shall be shaken in *the* day of her consummation.",
  "And [^4shall go ^1their kings ^2into ^3captivity,] their priests and their rulers together, says *the* LORD.",
];

// ---- Amos 1 — KJV (public domain) ----
const AMOS1_KJV = [
  "The words of Amos, who was among the herdmen of Tekoa, which he saw concerning Israel in the days of Uzziah king of Judah, and in the days of Jeroboam the son of Joash king of Israel, two years before the earthquake.",
  "And he said, The LORD will roar from Zion, and utter his voice from Jerusalem; and the habitations of the shepherds shall mourn, and the top of Carmel shall wither.",
  "Thus saith the LORD; For three transgressions of Damascus, and for four, I will not turn away the punishment thereof; because they have threshed Gilead with threshing instruments of iron:",
  "But I will send a fire into the house of Hazael, which shall devour the palaces of Benhadad.",
  "I will break also the bar of Damascus, and cut off the inhabitant from the plain of Aven, and him that holdeth the sceptre from the house of Eden: and the people of Syria shall go into captivity unto Kir, saith the LORD.",
  "Thus saith the LORD; For three transgressions of Gaza, and for four, I will not turn away the punishment thereof; because they carried away captive the whole captivity, to deliver them up to Edom:",
  "But I will send a fire on the wall of Gaza, which shall devour the palaces thereof:",
  "And I will cut off the inhabitant from Ashdod, and him that holdeth the sceptre from Ashkelon, and I will turn mine hand against Ekron: and the remnant of the Philistines shall perish, saith the Lord GOD.",
  "Thus saith the LORD; For three transgressions of Tyrus, and for four, I will not turn away the punishment thereof; because they delivered up the whole captivity to Edom, and remembered not the brotherly covenant:",
  "But I will send a fire on the wall of Tyrus, which shall devour the palaces thereof.",
  "Thus saith the LORD; For three transgressions of Edom, and for four, I will not turn away the punishment thereof; because he did pursue his brother with the sword, and did cast off all pity, and his anger did tear perpetually, and he kept his wrath for ever:",
  "But I will send a fire upon Teman, which shall devour the palaces of Bozrah.",
  "Thus saith the LORD; For three transgressions of the children of Ammon, and for four, I will not turn away the punishment thereof; because they have ripped up the women with child of Gilead, that they might enlarge their border:",
  "But I will kindle a fire in the wall of Rabbah, and it shall devour the palaces thereof, with shouting in the day of battle, with a tempest in the day of the whirlwind:",
  "And their king shall go into captivity, he and his princes together, saith the LORD.",
];

// ---- Lexicon (clickable lemmas) ----
const WORDS = {
  G1154: {
    en: "Damascus", greek: "Δαμασκός", translit: "Damaskós",
    morph: "PN", type: "Proper noun — place",
    cat: "place", tag: "NETAV",
    lsj: "Damascus, a city of Syria.",
    lsjFull: "Δαμασκός, ἡ — Damascus, the oldest continually-inhabited city of the ancient Near East and capital of the Aramean kingdom of Aram-Damascus; rendered for Hebrew דַּמֶּשֶׂק (Dammeśeq).",
    occ: "62 × in LXX", occVerse: "in the Septuagint",
    place: { region: "Syria", modern: "Dimashq", labels: ["LEBANON", "RIF DIMASHQ", "SUWEIDA", "AL-QUNEITRA"] },
  },
  H3389: { en: "Jerusalem", greek: "Ἰερουσαλήμ", translit: "Ierousalḗm", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Jerusalem, the holy city of Judah.", lsjFull: "Ἰερουσαλήμ — the capital of the kingdom of Judah; the site of the Temple. Transliterates Hebrew יְרוּשָׁלִַם.",
    occ: "643 × in LXX", place: { region: "Judah", modern: "Yerushalayim", labels: ["JUDEA", "BENJAMIN", "DEAD SEA"] } },
  H6726: { en: "Zion", greek: "Σιών", translit: "Siṓn", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Zion, the hill of Jerusalem.", lsjFull: "Σιών — originally the Jebusite stronghold captured by David; by extension the Temple mount and the city of Jerusalem as God's dwelling.",
    occ: "157 × in LXX", place: { region: "Jerusalem", modern: "Har Tsiyyon", labels: ["JERUSALEM", "KIDRON"] } },
  H3760: { en: "Carmel", greek: "Κάρμηλος", translit: "Kármēlos", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Carmel, a fruitful coastal range.", lsjFull: "Κάρμηλος — a wooded mountain ridge on the Mediterranean coast, proverbial for fertility; site of Elijah's contest with the prophets of Baal.",
    occ: "26 × in LXX", place: { region: "Israel", modern: "Har HaKarmel", labels: ["GALILEE", "HAIFA BAY"] } },
  H1568: { en: "Gilead", greek: "Γαλαάδ", translit: "Galaád", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Gilead, a region east of Jordan.", lsjFull: "Γαλαάδ — the mountainous pastoral region east of the Jordan, allotted to Gad, Reuben and half-Manasseh; renowned for its balm.",
    occ: "134 × in LXX", place: { region: "Transjordan", modern: "Jal'ad", labels: ["AMMON", "JORDAN R.", "BASHAN"] } },
  G4947: { en: "Syria", greek: "Συρία", translit: "Syría", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Syria, the region north of Israel.", lsjFull: "Συρία — the territory between the Mediterranean and the Euphrates, centred on Damascus; the Aramean lands of the Hebrew Bible.",
    occ: "73 × in LXX", place: { region: "Levant", modern: "Sūriyā", labels: ["DAMASCUS", "EUPHRATES", "ARAM"] } },
  H5804: { en: "Gaza", greek: "Γάζα", translit: "Gáza", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Gaza, a Philistine city.", lsjFull: "Γάζα — southernmost of the five Philistine cities, a key station on the coastal trade route to Egypt.",
    occ: "22 × in LXX", place: { region: "Philistia", modern: "Ghazzah", labels: ["PHILISTIA", "NEGEV", "SEA"] } },
  H123: { en: "Edom", greek: "Ἐδώμ", translit: "Edṓm", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Edom, the land of Esau's descendants.", lsjFull: "Ἐδώμ — the mountainous land south of the Dead Sea settled by the descendants of Esau; perennial rival of Israel.",
    occ: "98 × in LXX", place: { region: "South of Dead Sea", modern: "Udum", labels: ["SEIR", "ARABAH", "MOAB"] } },
  H3478: { en: "Israel", greek: "Ἰσραήλ", translit: "Israḗl", morph: "PN", type: "Proper noun — people / place", cat: "place", tag: "NETAV",
    lsj: "Israel, the covenant people.", lsjFull: "Ἰσραήλ — the name given to Jacob and to the nation descended from him; here the northern kingdom addressed by Amos.",
    occ: "2,500+ × in LXX", place: { region: "Canaan", modern: "Yisra'el", labels: ["SAMARIA", "JUDAH", "GALILEE"] } },
  H3063: { en: "Judah", greek: "Ἰούδα", translit: "Ioúda", morph: "PN", type: "Proper noun — people / place", cat: "place", tag: "NETAV",
    lsj: "Judah, the southern kingdom.", lsjFull: "Ἰούδα — the tribe and southern kingdom whose capital was Jerusalem; the home of Amos (Tekoa).",
    occ: "820 × in LXX", place: { region: "Southern Levant", modern: "Yehudah", labels: ["JERUSALEM", "HEBRON", "DEAD SEA"] } },
  H6865: { en: "Tyre", greek: "Τύρος", translit: "Týros", morph: "PN", type: "Proper noun — place", cat: "place", tag: "NETAV",
    lsj: "Tyre, a Phoenician port.", lsjFull: "Τύρος — the great Phoenician maritime city, famed for purple dye and far-flung trade.",
    occ: "48 × in LXX", place: { region: "Phoenicia", modern: "Ṣūr", labels: ["PHOENICIA", "SIDON", "SEA"] } },
  H5983: { en: "Ammon", greek: "Ἀμμών", translit: "Ammṓn", morph: "PN", type: "Proper noun — people", cat: "place", tag: "NETAV",
    lsj: "Ammon, a Transjordan people.", lsjFull: "Ἀμμών — the people descended from Lot, settled east of the Jordan around Rabbah; frequent antagonists of Israel.",
    occ: "106 × in LXX", place: { region: "Transjordan", modern: "'Ammān", labels: ["RABBAH", "GILEAD", "MOAB"] } },
  // people / non-place lemmas (no map)
  H5986: { en: "Amos", greek: "Ἀμώς", translit: "Amṓs", morph: "PN", type: "Proper noun — person", cat: "person", tag: "PROPH",
    lsj: "Amos, herdsman and prophet of Tekoa.", lsjFull: "עָמוֹס (ʿĀmôs) — 'burden-bearer'; a shepherd and dresser of sycamore figs from Tekoa, called to prophesy against the northern kingdom c. 760 BC.", occ: "7 × in OT" },
  H5818: { en: "Uzziah", greek: "Ὀζίας", translit: "Ozías", morph: "PN", type: "Proper noun — person", cat: "person", tag: "KING",
    lsj: "Uzziah, king of Judah.", lsjFull: "עֻזִּיָּהוּ (ʿUzziyyāhû) — 'Yahweh is my strength'; long-reigning king of Judah (also Azariah), under whom Amos prophesied.", occ: "27 × in OT" },
  H3379: { en: "Jeroboam", greek: "Ἱεροβοάμ", translit: "Hieroboám", morph: "PN", type: "Proper noun — person", cat: "person", tag: "KING",
    lsj: "Jeroboam II, king of Israel.", lsjFull: "יָרָבְעָם (Yārobʿām) — Jeroboam son of Joash, whose prosperous reign over the northern kingdom forms the backdrop of Amos.", occ: "104 × in OT" },
  H8010: { en: "Solomon", greek: "Σαλωμών", translit: "Salōmṓn", morph: "PN", type: "Proper noun — person", cat: "person", tag: "KING",
    lsj: "Solomon, son of David.", lsjFull: "שְׁלֹמֹה (Shəlomoh) — 'peaceable'; here used of a captive population given over in the slave trade.", occ: "293 × in OT" },
  H2371: { en: "Hazael", greek: "Ἀζαήλ", translit: "Azaḗl", morph: "PN", type: "Proper noun — person", cat: "person", tag: "KING",
    lsj: "Hazael, king of Aram-Damascus.", lsjFull: "חֲזָאֵל (Ḥăzāʾēl) — usurper-king of Damascus who oppressed Israel; his 'house' stands for the Aramean dynasty.", occ: "23 × in OT" },
};

const AMOS = {
  ab: "Amo", name: "Amos", ch: 9,
  text: { abp: AMOS1_ABP, kjv: AMOS1_KJV },
};

Object.assign(window, { BOOKS, WORDS, AMOS });
